name: 'Stale issue handler'
on:
  workflow_dispatch:
  schedule:
    - cron: '5 * * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: C0ZEN/stale@feature/team-assignees
        id: stale
        with:
          days-before-stale: 30
          days-before-close: 5
          exempt-assignees: C0ZEN
      - name: Print outputs
        run: echo ${{ join(steps.stale.outputs.*, ',') }}
